### ISSUE TITLE
Conflicting usernames cause issue with rank lookup

### ISSUE THREAD

**Issue by JimLiu0** [HS-Tools/HS-BG-Leaderboards-Bot#101]
Someone called pun is 25 and 72 on EU so !bgrank 25 eu gives an error.

**Comment by quinnabrvau** [comment]
bofur has 2 leaderboard accounts too, it does weird things for daily stats. I've never seen it fully break, it just doesn't track them

**Comment by JimLiu0** [comment]
Fixed with change to how we store data. I.e. if there's a 2nd moyi we store them as moyi2 and 3rd as moyi3. Still collision possibility with an existing moyi2 being in the db but there are collision checks in the logs now
