### ISSUE TITLE
give players who are off the leaderboard rank -1

### ISSUE THREAD

**Issue by quinnabrvau** [HS-Tools/HS-BG-Leaderboards-Bot#51]
`checkIfTimeIs30MinutesInThePast` doesn't seem like the best way to handle players dropping off the leaderboard. The better solution would be to go through the table and clear the rank for those who have fallen off.

**Comment by JimLiu0** [comment]
I was trying to keep DDB costs lower by not having to read the entire table and adjust ranks during the lambda function phase. I do agree that it is not a very good method. I think a db migration/overhaul is going to be needed to keep costs lower.

**Comment by quinnabrvau** [comment]
reasonable, for today's table and yesterdays table would it be better to just label tables by date? and then you just make a new one for each day?
are you exceeding the read/write for the free tier? maybe move the lambda functions down to the bot level?
