### ISSUE TITLE
Move leaderboard fetching to a Lambda Function

### ISSUE THREAD

**Issue by JimLiu0** [HS-Tools/HS-BG-Leaderboards-Bot#6]
Write a lambda function that will run on a CRON schedule and write to the managed DB.

**Comment by BoraxTheClean** [comment]
@JimLiu0 I am pretty capable of working on #5 and #6. Did you want to do these with me, so you can learn a bit as we go?

I also think the project would benefit from adding simple CI, similar to: https://github.com/BoraxTheClean/DevelopmentMachine/actions. GitHub actions are free for public repositories.
