### ISSUE TITLE
update provisioned throughput

### ISSUE THREAD

**Issue by quinnabrvau** [HS-Tools/HS-BG-Leaderboards-Bot#62]
I think part of the cost of the db is how it's provisioned. at the free tier you get 25 read and 25 write units. I think they should be distributed like the below table. My main logic, The majority of writes should be to the primary database, as with most of the reads. There could be a lot of reads on yesterday so it stays the same. There shouldn't be many writes to the side tables, so this should keep everything under the 25/25 free tier
```js
{
  'daily-rating-record-table': {
        ReadCapacityUnits: 10,
        WriteCapacityUnits: 20
  },
  'yesterday-rating-record-table': {
        ReadCapacityUnits: 10,
        WriteCapacityUnits: 1
  },
   'channel-table': {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1
  },
  'player-alias-table': {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1
  }
}
```

**Comment by JimLiu0** [comment]
This makes a lot of sense, I did not really understand how the units worked until I took a look at the docs

**Comment by JimLiu0** [comment]
Handled with #63
