### ISSUE TITLE
Drop PySLOBS dependency

### ISSUE THREAD

**Issue by Julian-O** [HS-Tools/HS-BG-Leaderboards-Bot#88]
I came to have a snoop to see how my PySLOBS library was being used, to see if I could see ways of improving it.

Turns out, you have a dependency on the library, but don't use it. That's not ideal; it is one more thing that can go wrong for no benefit.

Consider removing

    pyslobs = "*"

from Pipfile.

(If PySLOBS can be helpful, but there is something that is preventing you from using it, I would love to hear what.)

**Comment by JimLiu0** [comment]
I removed dependencies that I was just playing around with in the past, including pyslobs
